version: "3.8"
services:
  my_psql_service:
    image: "postgres"
    container_name: psql_container
    ports:
      - "54320:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pgacid